### PR TITLE
Use qualified ids for census API

### PR DESCRIPTION
**Pull request by leio10**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@leio10 Does this mean the connector no longer needs to know the "person id" in the census side, and thus, the `CREATE` endpoint no longer needs to inform the created person id? Seems like a good move to me!

**Comment by leio10** [comment]
@deivid-rodriguez yep :smirk:

**Comment by deivid-rodriguez** [comment]
So is the metadata "person_id" we were saving in the authorization no longer needed?

**Comment by leio10** [comment]
No, but I think we should keep it until we have everything more clear, maybe it could be useful to have it

**Comment by deivid-rodriguez** [comment]
Yeah, right now we're still depending on it since it's used to check if the user has an associated person in the census side. However, I find it now confusing and error prone to check for the presence of that id in `has_person?` but then use a different id to actually grab the person from the API.

Theoretically, now the `has_person?` method could ignore the person id metadata and just assume that if the user has an associated census authorization record, then the user has an associated person in the census side, right? If this is correct, I would go all the way and remove all "person_id" traces from this plugin.

Thoughts?

**Comment by leio10** [comment]
I made [some changes in census](https://github.com/podemos-info/census/pull/173) to get this PR working.

**Comment by leio10** [comment]
@deivid-rodriguez I returned to use census person ids in API calls in https://github.com/podemos-info/decidim-module-census_connector/pull/27/commits/452900d508466d7e94c38a50141ebc5cc2cf4cd1.

I also moved all the related logic to qualified ids (person id retrieval, qualified_ids generation, person data request from API) to a service. At the beginning it was called `UserPerson`, but CodeClimate complained and then I discovered that it had similar responsibilities to `PersonProxy` in models folder, so I unified both in a service class called `PersonProxy`.

What do you think about this? Should we merge this and let the census qualified discussion for later? :grimacing:

**Comment by deivid-rodriguez** [comment]
@leio10 Agree with everything:

* Your refactorings :muscle:
* Using census ids everywhere :heart:
* Having the discussion of removing qualified calls from the API separately :+1:

**Pull request merged**
